### ISSUE TITLE
Data fra Directus blir lagret som HTML - vis på fornuftig måte

### ISSUE THREAD

**Issue by akselkvitberg** [bcc-code/bcc-qr-code-run#6]
Nå vises `<p>` i teksten

**Comment by akselkvitberg** [comment]
![image](https://user-images.githubusercontent.com/5091899/192160628-e852311d-7416-4c45-917e-adf9c78d27c9.png)

**Comment by rvanoord** [comment]
Tips: bruk v-html="" og ingenting mellom start og slutt tag.
